### ISSUE TITLE
Error on Textfile

### ISSUE THREAD

**Issue by MAYKELL07** [typicode/steno#22]
const { Writer } = require('steno');
                   ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\Administrator\RaidenShogun-Bot\node_modules\steno\lib\index.js from C:\Users\Administrator\RaidenShogun-Bot\lib\lowdb\adapters\TextFile.js not supported.
Instead change the require of index.js in C:\Users\Administrator\RaidenShogun-Bot\lib\lowdb\adapters\TextFile.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Users\Administrator\RaidenShogun-Bot\lib\lowdb\adapters\TextFile.js:2:20)
    at Object.<anonymous> (C:\Users\Administrator\RaidenShogun-Bot\lib\lowdb\adapters\JSONFile.js:1:22)
    at Object.<anonymous> (C:\Users\Administrator\RaidenShogun-Bot\lib\lowdb\index.js:2:8)
    at Object.<anonymous> (C:\Users\Administrator\RaidenShogun-Bot\main.js:19:9) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by artegoser** [comment]
Are you serious?
